---
- name: Ensure Windows user is deleted
  hosts: os_windows
  gather_facts: no
  tasks:
    - name: Ensure user "unwanted_user" is created
      ansible.windows.win_user:
        name: unwanted_user
        state: Present

    - name: Ensure only a domain user exists in a local group
      ansible.windows.win_group_membership:
        name: Administrators
        members:
          - unwanted_user
        state: present

# - name: Ensure only a domain user exists in a local group
#   ansible.windows.win_group_membership:
#     name: Administrators
#     members:
#       - ec2-user
#       - Administrator
#       - admin
#     state: pure
