---

- name: Fix McAfee
  hosts: os_windows
  gather_facts: false

  tasks:
    # - name: Win ping - determine that we can access and run automation against the Windows host
    #   ansible.windows.win_ping:

    # - name: Create directory C:\Temp
    #   ansible.windows.win_file:
    #     path: C:\Temp
    #     state: directory

    # - name: Copy a single file (you have a PS1 file you don't need to update variables for)
    #   ansible.windows.win_copy:
    #     src: "{{ playbook_dir }}/files/test.ps1"
    #     dest: C:\Temp\test.ps1

    # - name: Create a file from a Jinja2 template (you have a PS1 file you need to update variables for)
    #   ansible.windows.win_template:
    #     src: ./add_user.j2
    #     dest: C:\Temp\add_user.ps1

    # - name: Execute a command in the remote shell, stdout goes to the specified file on the remote
    #   ansible.windows.win_shell: C:\Temp\add_user.ps1 >> C:\Temp\add_user_log.txt

    # - name: Remove add_user file, if present
    #   ansible.windows.win_file:
    #     path: C:\Temp\add_user.ps1
    #     state: absent

    # - name: Execute the McAfee cmdagent executable in the remote shell (powershell)
    #   ignore_errors: true
    #   ansible.windows.win_shell: c:\Program Files\McAfee\Agent\cmdagent.exe /p /e /c /f

    # - name: show netstat output
    #   ansible.builtin.win_command: "netstat -e"
    #   register: netstat_output

    # - name: Debug netstat output
    #   ansible.builtin.debug:
    #     var: netstat_output

    - name: Execute the McAfee cmdagent executable in the remote shell (powershell)
      ignore_errors: true
      ansible.windows.win_shell: Start-Process -FilePath MpCmdRun.exe '"-Scan -ScanType 2"'
      args:
        chdir: '"c:\Program Files\Windows Defender"'
        # MpCmdRun.exe -Scan -ScanType 2

    - name: Execute the McAfee cmdagent executable in the remote shell (powershell)
      ignore_errors: true
      ansible.windows.win_shell: |
        Start-Process -FilePath "c:\Program Files\Windows Defender\MpCmdRun.exe" '"-Scan -ScanType 2"'
      # Start-Process -FilePath "C:\Path with spaces\application.exe" -ArgumentList 'U=<username>', 'S=serverName', '"eg pathname with spaces as single argument"'


    - name: Run the McAfee cmdagent executable
      ignore_errors: true
      ansible.windows.win_command: invoke-command { "c:\Program Files\McAfee\Agent\cmdagent.exe /p /e /c /f" }
      register: result_new

    - name: Execute the McAfee cmdagent executable in the remote shell (powershell)
      ignore_errors: true
      ansible.windows.win_shell: |
        Start-Process -FilePath "c:\Program Files\McAfee\Agent\cmdagent.exe" '"/p /e /c /f"'
      # Start-Process -FilePath "C:\Path with spaces\application.exe" -ArgumentList 'U=<username>', 'S=serverName', '"eg pathname with spaces as single argument"'

    # - name: Run the McAfee cmdagent executable
    #   ignore_errors: true
    #   register: result_argv
    #   ansible.windows.win_command:
    #     # When using argv, each entry is quoted in the module
    #     argv:
    #       - c:\Program Files\McAfee\Agent\cmdagent.exe
    #       - /p
    #       - /e
    #       - /c
    #       - /f
...
